name: BubenBot Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100-preview.4.20258.7'

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: repo
          path: .

  push_amd64:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          # Artifact name
          name: repo
          # Destination path
          path: .
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: razkev/bubenbot
          dockerfile: Dockerfile
          tags: latest
  push_arm64:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          # Artifact name
          name: repo
          # Destination path
          path: .
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: razkev/bubenbot
          dockerfile: Dockerfile
          tags: arm64v8

# TODO: Deploy image
# deploy:
#   needs: push
#   runs-on: ubuntu-latest